# Generated by Django 5.1 on 2025-01-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
