# Generated by Django 5.1 on 2025-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_event_created_at_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
