# Generated by Django 5.1 on 2025-01-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_featuredevent_delete_highlight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedEvent',
        ),
    ]
